- hosts: all

  pre_tasks:
  - name: Instalar Python
    become: yes
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal && apt-install -y python-flask)

  tasks:
  - name: Actualizar
    become: yes
    command: apt-get update

  - name:  Git
    become: yes
    command: apt-get install -y git

  - name: Instalar pip
    become: yes
    command: apt-get install -y python-pip

  - name: Copiar Repo
    become: yes
    git: repo=https://github.com/marquirj/ProyectoSkull  dest=~/ProyectoSkull/ clone=yes force=yes

  - name: Instalar requirements
    become: yes
    command: pip install -r ~/ProyectoSkull/requirements.txt
